version: '3.6'

services:
  node:
    build: .
    image: dbservice
    container_name: dbservice
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      dbNetwork:
  database:
    build: ./db-init
    image: mydb
    container_name: mysqldb
    restart: always
    volumes:
     - my-sqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=db
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
    networks:
      dbNetwork:
volumes:
  my-sqldata:
    name: mysql
networks: 
  dbNetwork: